### ISSUE TITLE
ERROR in : Couldn't resolve resource ./claims-about.component.css relative to /app/src/app/claims-about.component.ts

### ISSUE THREAD

**Issue by twktheainur** [claimskg/claimskg-explorer#1]
Hi, 
I am updating the Docker deployment, and when I build my container, when ng build runs I encounter the following issue:
ERROR in : Couldn't resolve resource ./claims-about.component.css relative to /app/src/app/claims-about.component.ts

Do you have the same issue currently? If not, which version of Angular are you using the build? 

Best
@mgasquet

**Comment by mgasquet** [comment]
Hi,
Sorry, this was due to an unused misplaced file, I just delete it and update the git, everything should work now.

Best
@twktheainur

**Comment by twktheainur** [comment]
Hi, 
Thank you for the fix, everything seems to be in order now

 Best
